name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v2

      - name: Run linting
        run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.25@sha256:2595154b67df16b8bb9cf1ca01eeefe01bc18b68daa5ee745ba8edf2405be740
        with:
          args: -color
