name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v3

      - name: Run linting
        run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.27
        with:
          args: -color
